name: keep-alive

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Keep workflow alive
        uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
